# .github/workflows/ci.yml

name: iOS CI

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: macos-14

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Xcode Version
      run: sudo xcode-select --switch /Applications/Xcode_16.1.app
      shell: bash

    - name: Build for Testing
      run: |
        xcodebuild build-for-testing \
        -project GithubActions/GithubActions.xcodeproj \
        -scheme GithubActions \
        -destination 'platform=iOS Simulator,name=iPhone 16' \
          -derivedDataPath build
    - name: Test without Building
      run: |
        xcodebuild test-without-building \
        -xctestrun build/Build/Products/*.xctestrun \
        -destination 'platform=iOS Simulator,name=iPhone 16'
