name: iOS CI

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test:
    name: Build & Test on iOS 18.1 (Xcode 16.1, iPhone 16)
    runs-on: macos-14

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Select Xcode 16.1
        run: sudo xcode-select -s /Applications/Xcode_16.1.app

      - name: Show Xcode & macOS version
        run: |
          xcodebuild -version
          sw_vers

      - name: Clean DerivedData
        run: rm -rf build

      - name: Build for Testing
        run: |
          xcodebuild build-for-testing \
            -project GithubActions/GithubActions.xcodeproj \
            -scheme GithubActions \
            -destination 'platform=iOS Simulator,name=iPhone 16,OS=18.1' \
            -derivedDataPath build

      - name: Test without Building
        run: |
          XCTESTRUN_PATH=$(find build/Build/Products -name '*.xctestrun' | head -n 1)
          xcodebuild test-without-building \
            -xctestrun "$XCTESTRUN_PATH" \
            -destination 'platform=iOS Simulator,name=iPhone 16,OS=18.1'